# Generated by Django 4.1.7 on 2023-07-18 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='isPlaying',
            field=models.BooleanField(default=False),
        ),
    ]
