# Generated by Django 4.1.7 on 2023-07-18 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_market_isplaying'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='market',
            name='isPlaying',
        ),
        migrations.RemoveField(
            model_name='market',
            name='phone_number',
        ),
    ]
