# Generated by Django 5.1.6 on 2025-09-05 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_dee_listing_mm'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dee',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='dd',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='mm',
        ),
    ]
