# Generated by Django 4.1.7 on 2023-07-18 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_remove_market_isplaying_remove_market_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='phone_number',
            field=models.CharField(default='00000000000', max_length=15),
        ),
    ]
