# Generated by Django 5.1.6 on 2025-09-08 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_delete_dee_remove_listing_dd_remove_listing_mm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='currencyName',
            field=models.CharField(default='NGN', max_length=50),
        ),
    ]
