# Generated by Django 4.1.7 on 2023-07-18 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_market_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='phone_number',
            field=models.CharField(default='Not Provided', max_length=15),
        ),
    ]
