# Generated by Django 5.1.6 on 2025-09-29 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_conversation_message_friend'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-pinned', '-timestamp']},
        ),
        migrations.AddField(
            model_name='post',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
    ]
