# Generated by Django 5.1.6 on 2025-09-30 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_alter_post_options_post_pinned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.ForeignKey(blank=True, default='NGN', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='network.currency'),
        ),
    ]
