# Generated by Django 5.1.6 on 2025-09-04 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_ssmarketcomment_ssmarketimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SsMarketComment',
            new_name='MarketComment',
        ),
        migrations.RenameModel(
            old_name='SsMarketImage',
            new_name='MarketImage',
        ),
    ]
