# Generated by Django 5.1.6 on 2025-10-03 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_product_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
