# Generated by Django 4.1.7 on 2023-04-27 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_alter_user_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pics',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
    ]
