# Generated by Django 5.1.6 on 2025-10-09 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0012_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('follow', 'Follow'), ('comment', 'Comment'), ('purchase', 'Purchase'), ('message', 'Message'), ('post', 'Post'), ('system', 'System'), ('ai_daily', 'AI Daily'), ('daily_market_update', 'Daily Market Update')], max_length=20),
        ),
    ]
