# Generated by Django 4.0.6 on 2023-05-21 22:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0015_remove_post_likes_post_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postHover', to='network.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userHover', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
