# Generated by Django 5.1.6 on 2025-10-16 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0017_order_delivery_status_order_flutterwave_tx_ref_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, default=2, max_digits=10, null=True),
        ),
    ]
