# Generated by Django 4.0.6 on 2023-06-06 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0017_haha_maashaaallah_delete_hover'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
