# Generated by Django 5.1.6 on 2025-10-18 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0019_order_delivery_type_manualdelivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualdelivery',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Paid', 'Paid'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
