# Generated by Django 5.1.6 on 2025-10-18 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0020_alter_manualdelivery_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_currency',
            field=models.ForeignKey(default='NGN', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='network.currency'),
        ),
    ]
