# Generated by Django 5.1.6 on 2025-10-18 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0021_alter_order_order_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_currency',
            field=models.ForeignKey(default=18, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='network.currency'),
        ),
    ]
