# Generated by Django 4.0.6 on 2023-06-24 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0021_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='currency', to='network.currency'),
        ),
    ]
