# Generated by Django 5.1.6 on 2025-10-18 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0023_manualdelivery_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manualdelivery',
            name='order',
        ),
        migrations.AlterField(
            model_name='manualdelivery',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Paid', 'Paid'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Update In Orders', max_length=20),
        ),
    ]
