# Generated by Django 5.1.6 on 2025-10-18 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0024_remove_manualdelivery_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualdelivery',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manual_delivery', to='network.order'),
        ),
    ]
