# Generated by Django 4.1.7 on 2023-07-02 02:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0024_market_marketcategory_marketcurrency_marketimage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='market',
            name='watchlist',
        ),
        migrations.AddField(
            model_name='market',
            name='cart',
            field=models.ManyToManyField(blank=True, related_name='cart', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='market',
            name='isFeatured',
            field=models.BooleanField(default=False),
        ),
    ]
