# Generated by Django 4.1.7 on 2023-07-04 23:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0025_remove_market_watchlist_market_cart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctions_comment',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=1.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marketcomment',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
