# Generated by Django 5.1.6 on 2025-10-18 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0025_manualdelivery_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
