# Generated by Django 4.1.7 on 2023-07-05 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0026_auctions_comment_timestamp_marketcomment_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctions_comment',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marketcomment',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
