# Generated by Django 4.1.7 on 2023-07-05 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0027_alter_auctions_comment_timestamp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctions_comment',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='marketcomment',
            name='timestamp',
        ),
    ]
