from django.contrib import admin
from .models import *

# Register your models here.
admin.site.register(LibraryImage)
admin.site.register(SharePost)
admin.site.register(GroupShare)
admin.site.register(User)
admin.site.register(PostImage)
admin.site.register(Announcement)
admin.site.register(AnnouncementPostImage)
admin.site.register(ForumTopicImage)
admin.site.register(LibraryCategory)
admin.site.register(LibraryDocument)
admin.site.register(Video)
admin.site.register(FavoriteDocument)
admin.site.register(FavoriteVideo)
admin.site.register(GroupPostImage)
admin.site.register(ForumPost)
admin.site.register(ForumTopic)
admin.site.register(Follow)
admin.site.register(Post)
admin.site.register(Comment)
admin.site.register(Like)
admin.site.register(Sad)
admin.site.register(Love)
admin.site.register(Haha)
admin.site.register(Shock)
admin.site.register(Group)
admin.site.register(GroupPost)
admin.site.register(GroupComment)
admin.site.register(GroupLike)
admin.site.register(GroupSad)
admin.site.register(GroupLove)
admin.site.register(GroupHaha)
admin.site.register(GroupShock)
admin.site.register(Listing)
admin.site.register(Category)
admin.site.register(auctions_Comment)
admin.site.register(Bid)
admin.site.register(Currency)
admin.site.register(Market)
admin.site.register(MarketCurrency)
admin.site.register(MarketComment)
admin.site.register(MarketImage)
admin.site.register(MarketCategory)
